server:
  port: 7000

spring:
  application:
    # 应用名称。
    # 为了便于管理和维护，需要将集群内的所有节点都设置为一样的应用名称。
    name: spring-cloud-eureka-server

eureka:
  instance:
    hostname: localhost

  client:
    registerWithEureka: false
    fetchRegistry: false
    service-url:
      defaultZone: http://localhost:7000/eureka/
  