server:
  port: 8002

spring:
  application:
    name: cloudproducer

eureka:
  client:
    service-url:
        defaultZone: http://eureka7000.com:7000/eureka/
  instance:
    instance-id: cloudproducer8002
    prefer-ip-address: true

info:
  app.name: cloudproducer
  company.name: www.study.com

